### ISSUE TITLE
process.env.SLS_MONGODB_URI

### ISSUE THREAD

**Issue by tarambuka** [bealearts/serverless-mongodb-local#1]
Hello,
I see here 
`    const client = await MongoClient.connect(
      process.env.SLS_MONGODB_URI,
      { useUnifiedTopology: true }
    );`

but what should be process.env.SLS_MONGODB_URI value because I get 'MongoParseError'?

**Comment by DavidBeale** [comment]
It should be a MongoDB connection string, such as `mongodb://127.0.0.1:56959/MyDB?`.

This is also logged out during startup: `mongodb-local: MongoDB started with; url: mongodb://127.0.0.1:56959/MyDB?, dbPath: ...`

**Comment by tarambuka** [comment]
Thank you very much @DavidBeale !
I couldn't see the `mongodb://127.0.0.1:1234/MyDB` because I was running `sls offline` command and Mongo actually wasn't started. When I use `sls offline start --config serverless.yml --noPrependStageInUrl` it's fine.
Thank you again !

**Comment by DavidBeale** [comment]
Ok, great. 

I'll update the README to include the start command.
