### ISSUE TITLE
process.env.SLS_MONGODB_URI is undefined

### ISSUE THREAD

**Issue by gsavvidis96** [bealearts/serverless-mongodb-local#11]
`console.log(process.env.SLS_MONGODB_URI);` inside lambda handler is undefined.

`serverless --version`: 
  Framework Core: 3.25.1 (local) 3.25.0 (global)
  Plugin: 6.2.2
  SDK: 4.3.2

package.json: 

  "devDependencies": {
      "serverless-mongodb-local": "^1.5.2",
      "serverless-offline": "^12.0.2"
  }

When doing `serverless offline start` I get: mongodb-local: MongoDB started with; url: mongodb://127.0.0.1:57647/ which means it runs correctly. So the only issue is I cannot have access to the environment variable. If it cannot be done via an environment variable, is there any other way to access the mongoUri inside the handler?

I have created a repo to reproduce: https://github.com/gsavvidis96/serverless-mongodb-local-test

**Comment by DavidBeale** [comment]
Looks like you now need to add a `--localEnvironment` flag on the command line 
e.g. `serverless offline start --localEnvironment`

**Comment by gsavvidis96** [comment]
Thank you! it works :)
