### ISSUE TITLE
Does not seem to work with local func invocations, does it? 

### ISSUE THREAD

**Issue by vadymhimself** [bealearts/serverless-mongodb-local#2]

**Comment by vadymhimself** [comment]
With `sls invoke local -f func`

**Comment by DavidBeale** [comment]
No. It is intended to be used with `sls offline start`, which has lifecycle events which are used to start and stop the MongoDB instance.

**Comment by vadymhimself** [comment]
@DavidBeale appreciate if you made it work with local invocations as well!

**Comment by DavidBeale** [comment]
Hi. If you update to v1.2.0 then you can use `sls mongodb start` on the command line.

**Comment by vadymhimself** [comment]
Looks like a solution! But the convenience env var is still not injected on local invocations

**Comment by DavidBeale** [comment]
No, it won't be. You need to run in the same process for that to work. i.e. using `serverless-offline`
